use_frameworks!

platform :ios, '9.0'

# 忽略pod第三方库文件警告
inhibit_all_warnings!

target 'PoporRotate_Example' do
  pod 'PoporRotate', :path => '../'
  
  pod 'Masonry'
  
  target 'PoporRotate_Tests' do
    inherit! :search_paths

    
  end
end
